--!strict
wait(3)
local controllers = script.Parent:WaitForChild("Controllers")

local BoardController = require(controllers:WaitForChild("BoardController"))
local GamePassController = require(controllers:WaitForChild("GamePassController"))
local HUDController = require(controllers:WaitForChild("HUDController"))
local LivePickingController = require(controllers:WaitForChild("LivePickingController"))
local LeaderboardController = require(controllers:WaitForChild("LeaderboardController"))
local LeaderboardDummyController = require(controllers:WaitForChild("LeaderboardDummyController"))
local MusicController = require(controllers:WaitForChild("MusicController"))
local MobileJumpController = require(controllers:WaitForChild("MobileJumpController"))
local NotificationController = require(controllers:WaitForChild("NotificationController"))
local ResultBoardController = require(controllers:WaitForChild("ResultBoardController"))
local ResultPopupController = require(controllers:WaitForChild("ResultPopupController"))
local SoundController = require(controllers:WaitForChild("SoundController"))
local TopbarCameraController = require(controllers:WaitForChild("TopbarCameraController"))
local WinDropController = require(controllers:WaitForChild("WinDropController"))

NotificationController.Init()
MobileJumpController.Init()
BoardController.Init()
GamePassController.Init()
HUDController.Init()
LivePickingController.Init()
LeaderboardDummyController.Init()
LeaderboardController.Init()
ResultBoardController.Init()
ResultPopupController.Init()
SoundController.Init()
MusicController.Init()
TopbarCameraController.Init()
WinDropController.Init()
